language: rust

rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3

script:
  - python3 build_script.py

matrix:
  allow_failures:
    - rust: nightly
