addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - python3

language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_script:
  - cargo install cargo-deadlinks

script:
  - python build_script.py

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  kcov --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/input_stream-* &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

matrix:
  include:
    - os: osx
      rust:
        - stable
        - nightly
  allow_failures:
    - rust: nightly
