language: rust

rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3

script:
  - python3 build_script.py

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/input_stream-*

matrix:
  allow_failures:
    - rust: nightly
